apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: mcp-tool-sscs-context-svc
  janus-idp.io/tekton: mcp-tool-sscs-context-svc
  backstage.io/kubernetes-id: mcp-tool-sscs-context-svc
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: mcp-tool-sscs-context-svc
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
  - serviceaccount.yaml
