apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: mcp-tool-sscs-context-svc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mcp-tool-sscs-context-svc 
  name: mcp-tool-sscs-context-svc
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: mcp-tool-sscs-context-svc 
